---
# vars required for managing VLANs
vlan_id: null
vlan_name: null

# vars optional for managing trunk ports
trunked_vlans: null

# vars required for managing ports
port_name: null
port_description: null
