---
# params to impliment trunking
trunked_vlans: "{{ trunked_vlans }}"

# params to implement port resource
#
port_name: "{{ port_name }}"
port_description: "{{ port_description }}"

# immediate STP forwarding
#
stp_edge: false
